{
 "title": "Zebra Status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Node Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zebrad_build_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zcash_chain_verified_block_height"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zcash_net_peers" }
   ]
  },
  { "title": "Network Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(zcash_net_in_bytes_total[1m]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(zcash_net_out_bytes_total[1m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(zcash_net_in_messages[1m]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(zcash_net_out_messages[1m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  { "title": "Consensus & Mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "zcash_mempool_size_transactions",
     "legendFormat": "Transactions"
    },
    { "expr": "zcash_mempool_size_bytes", "legendFormat": "Size (Bytes)" }
   ]
  },
  {
   "title": "Verification Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(proofs_halo2_verified[1m]) + rate(proofs_groth16_verified[1m])",
     "legendFormat": "Verifications/sec"
    }
   ]
  },
  { "title": "Peer Analytics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Peer Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (user_agent) (zcash_net_peers_connected)",
     "legendFormat": "{{user_agent}}"
    }
   ]
  }
 ]
}