backend = "fetch"
network = "Regtest"

[json_server_settings]
json_rpc_listen_address = "0.0.0.0:8237"

[grpc_settings]
grpc_listen_address = "0.0.0.0:8137"

[validator_settings]
validator_jsonrpc_listen_address = "zebra:18232"
